export const projects = [
  {
    id: 1,
    name: "FAQ Accordion",
    level: "Basic",
    suggestedBy: "Frontend Mentor",
    tech_stack: ["HTML", "CSS", "JAVASCRIPT"],
    description: "A simple FAQ accordion made with vanilla JavaScript.",
    url: "https://www.frontendmentor.io/solutions/responsive-faaccordion-component-bEhs19Hqkz",
    live_url: "https://codacad.github.io/fa-accordion/",
    gh_url: "https://github.com/Codacad/fa-accordion",
    ui_img:"/personal-portfolio/src/assets/projects-images/faq-accrodion.jpg",
    created_at: "17 December 2023",
  },
  {
    id: 2,
    name: "Responsive Advice Generator App",
    level: "Basic",
    suggestedBy: "Frontend Mentor",
    tech_stack: ["REACTJS", "REST API"],
    description: `An app that generates random advice built with ReactJS.`,
    url: "https://www.frontendmentor.io/solutions/responsive-advice-generator-app-zr4Boh0XF_",
    live_url: "https://codacad.github.io/advice-generator-app/",
    gh_url: "https://github.com/Codacad/advice-generator-app",
    ui_img:"/personal-portfolio/src/assets/projects-images/advice-generator-app.jpg",
    created_at: "14 December 2023",
  },
  {
    id: 3,
    name: "Responsive Expenses Chart Component",
    description:
      "A responsive expense chart component created using HTML< CSS & JS.",
    level: "Intermediate",
    suggestedBy: "Frontend Mentor",
    tech_stack: ["HTML", "CSS", "JAVASCRIPT"],
    url: "https://www.frontendmentor.io/solutions/responsive-expenses-chart-component-zS_-pDM-7i",
    live_url: "https://codacad.github.io/expenses-chart-component/",
    gh_url: "https://github.com/Codacad/expenses-chart-component",
    ui_img:"/personal-portfolio/src/assets/projects-images/expense-chart-component.jpg",
    created_at: "13 December 2023",
  },
  {
    id: 4,
    name: "QR Code Component",
    description: "A QR code component created in HTML & CSS",
    level: "Basic",
    suggestedBy: "Frontend Mentor",
    tech_stack: ["HTML", "CSS"],
    url: "https://www.frontendmentor.io/solutions/qr-code-component-BvEWmtWmBk",
    live_url: "https://codacad.github.io/qr-code-component/",
    gh_url: "https://github.com/Codacad/qr-code-component",
    ui_img:"/personal-portfolio/src/assets/projects-images/qr-component.jpg",
    created_at: "09 December 2023",
  },
  {
    id: 5,
    name: "Order Summary Component",
    description: "An order summary component created using HTML & CSS",
    level: "Basic",
    suggestedBy: "Frontend Mentor",
    tech_stack: ["HTML", "CSS"],
    url: "https://www.frontendmentor.io/solutions/order-summary-component-qZJqppKmMx",
    live_url: "https://codacad.github.io/order-summary-component/",
    gh_url: "https://github.com/Codacad/order-summary-component",
    ui_img:"/personal-portfolio/src/assets/projects-images/order-summary-component.jpg",
    created_at: "10 December 2023",
  },
  {
    id: 6,
    name: "Product Preview Card Component with React",
    description:
      "A product preview card component created using React and TailwindCSS.",
    level: "Basic",
    suggestedBy: "Frontend Mentor",
    tech_stack: ["REACTJS", "TAILWINDCSS"],
    url: "https://www.frontendmentor.io/solutions/product-preview-card-component-with-react-XA6NWcm8iD",
    live_url: "https://codacad.github.io/product-preview-card-component/",
    gh_url: "https://github.com/Codacad/product-preview-card-component",
    ui_img:"/personal-portfolio/src/assets/projects-images/product-preview-card-component.jpg",
    created_at: "29 November 2023",
  },
  {
    id: 7,
    name: "New Home Page (ReactJS, CSS, Responsive Design)",
    level: "Basic",
    suggestedBy: "Frontend Mentor",

    description:
      "A product preview card component created using React and TailwindCSS.",
    tech_stack: ["REACTJS", "TAILWINDCSS"],
    url: "https://www.frontendmentor.io/solutions/new-home-page-reactjs-css-responsive-design-dNLwzRf0mw",
    live_url: "https://codacad.github.io/news-homepage/",
    gh_url: "https://github.com/Codacad/news-homepage",
    ui_img:"/personal-portfolio/src/assets/projects-images/new-homepage.jpg",
    created_at: "07 October 2023",
  },
  {
    id: 8,
    name: "Intro Section with Dropdown (ReactJS, CSS, JavaScript, Reach Hooks)",
    level: "Basic",
    suggestedBy: "Frontend Mentor",
    description:
      "A dropdown menu that displays additional information when a user hovers over an item on the intro section of a landing page.",
    tech_stack: ["REACTJS"],
    url: "https://www.frontendmentor.io/solutions/intro-section-with-dropdown-reactjs-css-javascript-reach-hooks-n3JMrnV2jt",
    live_url: "https://codacad.github.io/Intro-Section-With-Dropdown/",
    gh_url: "https://github.com/Codacad/Intro-Section-With-Dropdown",
    ui_img:"/personal-portfolio/src/assets/projects-images/intro-section-with-dropdown-navigation.jpg",
    created_at: "07 October 2023",
  },
  {
    id: 9,
    name: "Newsletter Signup Form with Success Message",
    level: "Intermediate",
    suggestedBy: "Frontend Mentor",
    description:
      "A newsletter sign up form that displays a success message when the email is submitted.",
    tech_stack: ["HTML", "CSS", "JAVASCRIPT"],
    url: "https://www.frontendmentor.io/solutions/newsletter-signup-form-with-success-message-dP72UrE_l3",
    live_url: "https://codacad.github.io/newsletter-signup/",
    gh_url: "https://github.com/Codacad/newsletter-signup",
    ui_img:"/personal-portfolio/src/assets/projects-images/Newsletter Signup Form with Success Message.jpg",
    created_at: "09 July 2023",
  },
  {
    id: 10,
    name: "Interactive Rating Component",
    level: "Intermediate",
    suggestedBy: "Frontend Mentor",
    description: "An interactive rating component made in VanillaJS",
    tech_stack: ["HTML", "CSS", "JAVASCRIPT"],
    url: "https://www.frontendmentor.io/solutions/interactive-rating-component-gltf8Q6MVY",
    live_url: "https://codacad.github.io/rating-component/",
    gh_url: "https://github.com/Codacad/rating-component",
    ui_img:"/personal-portfolio/src/assets/projects-images/Interactive Rating Component.jpg",
    created_at: "20 July 2023",
  },
  {
    id: 11,
    name: "Sunnyside Agency Landing Page",
    level: "Basic",
    suggestedBy: "Frontend Mentor",
    description:
      "A landing page for a digital agency showcasing services, built using HTML, CSS, and JavaScript.",
    tech_stack: ["REACTJS"],
    url: "https://www.frontendmentor.io/solutions/sunnyside-agency-landing-page-3fQlY2DJlg",
    live_url: "https://codacad.github.io/sunnyside-agency-landing-opage/",
    gh_url: "https://github.com/Codacad/sunnyside-agency-landing-opage",
    ui_img:"/personal-portfolio/src/assets/projects-images/sunnyside-agency-lending-page.jpg",
    created_at: "01 October 2023",
  },
  {
    id: 12,
    name: "Responsive Results Summary Component",
    level: "Basic",
    suggestedBy: "Frontend Mentor",
    description:
      "A responsive results summary component built using HTML & CSS",
    tech_stack: ["HTML", "CSS"],
    url: "https://www.frontendmentor.io/solutions/responsive-results-summary-component-aHvCQ51p4V",
    live_url: "https://codacad.github.io/result-summary-component/",
    gh_url: "https://github.com/Codacad/result-summary-component",
    ui_img:"/personal-portfolio/src/assets/projects-images/Responsive Results Summary Component.jpg",
    created_at: "09 July 2023",
  },
  {
    id: 13,
    name: "Responsive landing page using CSS Grid & Flexbox",
    level: "Intermediate",
    suggestedBy: "Frontend Mentor",
    description:
      "A responsive design of a landing page using CSS grid and flexbox.",
    tech_stack: ["HTML", "CSS", "JAVASCRIPT"],
    url: "https://www.frontendmentor.io/solutions/responsive-landing-page-using-css-grid-and-flexbox-y72T9xYG-",
    live_url: "https://codacad.github.io/frontendmentor-challenge-1/",
    gh_url: "https://github.com/Codacad/frontendmentor-challenge-1",
    ui_img:"/personal-portfolio/src/assets/projects-images/Responsive landing page using CSS Grid & Flexbox.jpg",
    created_at: "12 March 2022",
  },
  {
    id: 14,
    name: "Interactive Quiz App",
    level: "Intermediate",
    suggestedBy: "Self Suggested",
    description:
      "This is an Interactive quiz app that I developed using MERN Stack",
    tech_stack: ["REACTJS", "NODEJS", "EXPRESSJS", "MONGODB"],
    url: "",
    live_url: "https://interactive-quiz-app-o2m7.vercel.app/",
    gh_url: "https://github.com/Codacad/interactive-quiz-app",
    created_at: "03 November 2023",
  },
  {
    id: 15,
    name: "Notification Page",
    level: "Intermediate",
    suggestedBy: "Self Suggested",
    tech_stack: ["REACTJS"],
    description: `A notification system for user to see the notifications they have received. Created with ReactJS`,
    url: "",
    live_url: "https://codacad.github.io/notifications-page/",
    gh_url: "https://github.com/Codacad/notifications-page",
    created_at: "17 December 2023",
  },
];